services:
  frontend:
    container_name: frontend
    build: ./front-end
    environment:
      - NODE_ENV=production
    ports:
      - 5000:3000
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    ports:
      - '8080:80' # Map container's port 80 to host's port 8080
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - '8081:80' # Map container's port 80 to host's port 8081
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: 'host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5'

  postgres:
    image: 'postgres:14.2'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - go-pgdata:/var/lib/postgresql/data

volumes:
  go-pgdata:
    driver: local
  # mail-service:
  #   build:
  #     context: ./mail-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:8181"  # Map container's port 8181 to host's port 80
  #   environment:
  #     - ANOTHER_ENV=value

  # Add more services as needed
