apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: "oxyprogrammer/authentication-service:1.0.0"
        env:
        - name: DSN
          value: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
        ports:
        - containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
  - protocol: TCP
    name: main-port
    port: 27017
    targetPort: 27017
